name: Workflow
on:
  push:
    branches:
      - feat-devsecops

jobs:        
  SAST:
    runs-on: ubuntu-latest
    steps:

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Hola Mundo
      run: | 
        echo 'Hola mundo!'

    - name: Build
      run: | 
        chmod 777 gradlew
        ./gradlew build

    - name: Validando existencia de proyecto en SonarCloud
      id: validateProjectOnSonar
      run: |
        set +e
        curl -f -X POST -u '${{ secrets.SONAR_TOKEN }}:' 'https://sonarcloud.io/api/projects/create' -d 'name=devops-v7_pet-clinic' -d 'project=devops-v7_pet-clinic' -d 'organization=devops-v7' -d 'visibility=public'
        if [ $? -ne 0 ]; then
          echo "Proyecto ya existe en Sonarcloud"
          echo "::set-output name=proyectoExiste::1"
        else
          echo "Proyecto devops-v7_pet-clinic creado exitosamente en Sonarcloud"
          
          echo "Se establece rama main como rama por defecto"
          curl -X POST -u '${{ secrets.SONAR_TOKEN }}:' 'https://sonarcloud.io/api/project_branches/set_branch_type' -d 'name=main' -d 'project=devops-v7_pet-clinic'
        fi
        set -e

    - name: Validando tipo de proyecto
      id: tipoProyecto
      if: steps.validateProjectOnSonar.outputs.proyectoExiste == '1'
      run: |
        pwd
        ls -R
        if [ -f "build.gradle" ]
        then
          echo "Proyecto Java"
          if grep -q 'id "org.sonarqube" version "3.3"' build.gradle
          then
            echo "El plugin de SonarCloud ya está presente en build.gradle"
          else
            sed -i '/id '\''java'\''/a \ \ \ \ id '\''org.sonarqube'\'' version '\''3.3'\''' build.gradle
            echo "El plugin de SonarCloud no estaba presente y se ha sido añadido a build.gradle"
            cat build.gradle
          fi

        else
          echo "Tipo de proyecto desconocido"
        fi

    - name: Enable execution gradlew
      run: | 
        chmod 777 gradlew

    - name: Print SonarQube Variables
      run: |
        echo "Project Key: devops-v7_pet-clinic"
        echo "Organization: devops-v7"
        echo "Token: ${{ secrets.SONAR_TOKEN }}"

    - name: Run SonarQube analysis
      run: |
        ./gradlew sonarqube --stacktrace --info \
        -Dsonar.token=${{ secrets.SONAR_TOKEN }} \
        -Dsonar.host.url=https://sonarcloud.io \
        -Dsonar.organization=devops-v7 \
        -Dsonar.projectKey=devops-v7_pet-clinic \
        -Dsonar.branch.name=feat-devsecops
