name: Workflow 
on:
  push:
    branches:
      - feat-devsecops

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: build
      run:  |
        chmod 777 gradlew
        ./gradlew build

    - name: Validando tipo de proyecto
      id: tipoProyecto
      if: step.validateProjectOnSonar.outputs.protectoExiste == '1'
      run: |
        if [ -f "build.gradle" ]; then
          echo "Proyecto Java"
        elif grep -q 'id "org.sonarqube" version "3.3"' build.gradle
        then
          echo "El plugin de sonarqube ya esta presente en build.gradle"
        else  
          sed -i '/id '\''java'\''/a \ \ \ \ id '\''org.sonarqube'\'' version '\''3.3'\''' build.gradle
          echo "El plugin de sonarqube no estaba presente y se ha añadido en build.gradle"
          cat build.gradle
        fi

    - name: Validando existencia de proyecto en Sonarcloud
      id: validateProjectOnSonar
      run: |
        set +e
        curl -f -X POST -u '${{secrets.TEST_DEVOPS}}:' 'https://sonarcloud.io/api/projects/create' -d 'name=${{github.event.repository.name}}' -d 'project=${{github.event.repository.name}}' -d 'organization=devops-v7' -d 'visibility=public'
        if [ $? -ne 0 ]
        then
          echo "Proyecto ya existe en Sonarcloud"
        else
          echo "Proyecto ${{github.event.repository.name}} fue creado exitosamente en Sonarcloud"

          echo "se establece rama main como rama por defecto"
          curl -X POST -u '${{secrets.TEST_DEVOPS}}:' 'https://sonarcloud.io/api/projects_branches/rename' -d 'name=main' -d 'project=${{github.event.repository.name}}'
        fi

    - name: Enable execution gradlew
      run: |
        chmod 777 gradlew

    - name: Run sonarqube analysis  
      run: |
        ./gradlew sonarqube \
        -Dsonar.projectKey=${{ github.event.repository.name }} \
        -Dsonar.organization=curso-devsecops-usach-test \
        -Dsonar.host.url=https://sonarcloud.io \
        -Dsonar.login=${{ secrets.TEST_DEVOPS }} \
        -Dsonar.branch.name=feat-devsecops
